import 'package:genotek_test_app/src/features/price_table/domain/models/price_item.dart';

enum Currency {
  clp('CLP', 'Chilean Peso', 'CL\$'),
  eur('EUR', 'Euro', '€'),
  pen('PEN', 'Peruvian Sol', 'S/'),
  usd('USD', 'US Dollar', '\$'),
  aed('AED', 'UAE Dirham', 'د.إ'),
  all('ALL', 'Albanian Lek', 'L'),
  amd('AMD', 'Armenian Dram', '֏'),
  aoa('AOA', 'Angolan Kwanza', 'Kz'),
  aud('AUD', 'Australian Dollar', 'A\$'),
  bam('BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM'),
  bdt('BDT', 'Bangladeshi Taka', '৳'),
  czk('CZK', 'Czech Koruna', 'Kč'),
  dkk('DKK', 'Danish Krone', 'kr'),
  dzd('DZD', 'Algerian Dinar', 'د.ج'),
  egp('EGP', 'Egyptian Pound', 'E£'),
  etb('ETB', 'Ethiopian Birr', 'Br'),
  gel('GEL', 'Georgian Lari', '₾'),
  hkd('HKD', 'Hong Kong Dollar', 'HK\$'),
  huf('HUF', 'Hungarian Forint', 'Ft'),
  inr('INR', 'Indian Rupee', '₹'),
  kes('KES', 'Kenyan Shilling', 'KSh'),
  kgs('KGS', 'Kyrgyzstani Som', 'с'),
  kzt('KZT', 'Kazakhstani Tenge', '₸'),
  mad('MAD', 'Moroccan Dirham', 'د.م.'),
  mdl('MDL', 'Moldovan Leu', 'L'),
  mxn('MXN', 'Mexican Peso', 'Mex\$'),
  myr('MYR', 'Malaysian Ringgit', 'RM'),
  ngn('NGN', 'Nigerian Naira', '₦'),
  npr('NPR', 'Nepalese Rupee', 'रु'),
  nzd('NZD', 'New Zealand Dollar', 'NZ\$'),
  php('PHP', 'Philippine Peso', '₱'),
  pkr('PKR', 'Pakistani Rupee', '₨'),
  pln('PLN', 'Polish Złoty', 'zł'),
  qar('QAR', 'Qatari Riyal', 'ر.ق'),
  ron('RON', 'Romanian Leu', 'lei'),
  rsd('RSD', 'Serbian Dinar', 'дин'),
  sar('SAR', 'Saudi Riyal', 'ر.س'),
  sek('SEK', 'Swedish Krona', 'kr'),
  sgd('SGD', 'Singapore Dollar', 'S\$'),
  thb('THB', 'Thai Baht', '฿'),
  tjs('TJS', 'Tajikistani Somoni', 'SM'),
  zar('ZAR', 'South African Rand', 'R'),
  uyu('UYU', 'Uruguayan Peso', '\$U'),
  chf('CHF', 'Swiss Franc', 'CHF'),
  nok('NOK', 'Norwegian Krone', 'kr'),
  rub('RUB', 'Russian Ruble', '₽'),
  gbp('GBP', 'British Pound Sterling', '£');

  final String code;
  final String name;
  final String symbol;

  const Currency(this.code, this.name, this.symbol);

  @override
  String toString() => '$name ($symbol)';
}

extension CurrencyPriceItemExtensions on Currency {
  bool getDiscountState(PriceItem item) {
    final discountStates = {
      Currency.clp: item.discountStateCl,
      Currency.eur: item.discountStateEu,
      Currency.pen: item.discountStatePen,
      Currency.usd: item.discountStateUsd,
      Currency.aed: item.discountStateAed,
      Currency.all: item.discountStateAll,
      Currency.amd: item.discountStateAmd,
      Currency.aoa: item.discountStateAoa,
      Currency.aud: item.discountStateAud,
      Currency.bam: item.discountStateBam,
      Currency.bdt: item.discountStateBdt,
      Currency.czk: item.discountStateCzk,
      Currency.dkk: item.discountStateDkk,
      Currency.dzd: item.discountStateDzd,
      Currency.egp: item.discountStateEgp,
      Currency.etb: item.discountStateEtb,
      Currency.gel: item.discountStateGel,
      Currency.hkd: item.discountStateHkd,
      Currency.huf: item.discountStateHuf,
      Currency.inr: item.discountStateInr,
      Currency.kes: item.discountStateKes,
      Currency.kgs: item.discountStateKgs,
      Currency.kzt: item.discountStateKzt,
      Currency.mad: item.discountStateMad,
      Currency.mdl: item.discountStateMdl,
      Currency.mxn: item.discountStateMxn,
      Currency.myr: item.discountStateMyr,
      Currency.ngn: item.discountStateNgn,
      Currency.npr: item.discountStateNpr,
      Currency.nzd: item.discountStateNzd,
      Currency.php: item.discountStatePhp,
      Currency.pkr: item.discountStatePkr,
      Currency.pln: item.discountStatePln,
      Currency.qar: item.discountStateQar,
      Currency.ron: item.discountStateRon,
      Currency.rsd: item.discountStateRsd,
      Currency.sar: item.discountStateSar,
      Currency.sek: item.discountStateSek,
      Currency.sgd: item.discountStateSgd,
      Currency.thb: item.discountStateThb,
      Currency.tjs: item.discountStateTjs,
      Currency.zar: item.discountStateZar,
      Currency.uyu: item.discountStateUyu,
      Currency.chf: item.discountStateChf,
      Currency.nok: item.discountStateNok,
      Currency.rub: item.discountState,
      Currency.gbp: item.discountStateGbp,
    };
    return discountStates[this] ?? false;
  }

  double? getStartPrice(PriceItem item) {
    final startPrices = {
      Currency.clp: item.startPriceCl,
      Currency.eur: item.startPriceEu,
      Currency.pen: item.startPricePen,
      Currency.usd: item.startPriceUsd,
      Currency.aed: item.startPriceAed,
      Currency.all: item.startPriceAll,
      Currency.amd: item.startPriceAmd,
      Currency.aoa: item.startPriceAoa,
      Currency.aud: item.startPriceAud,
      Currency.bam: item.startPriceBam,
      Currency.bdt: item.startPriceBdt,
      Currency.czk: item.startPriceCzk,
      Currency.dkk: item.startPriceDkk,
      Currency.dzd: item.startPriceDzd,
      Currency.egp: item.startPriceEgp,
      Currency.etb: item.startPriceEtb,
      Currency.gel: item.startPriceGel,
      Currency.hkd: item.startPriceHkd,
      Currency.huf: item.startPriceHuf,
      Currency.inr: item.startPriceInr,
      Currency.kes: item.startPriceKes,
      Currency.kgs: item.startPriceKgs,
      Currency.kzt: item.startPriceKzt,
      Currency.mad: item.startPriceMad,
      Currency.mdl: item.startPriceMdl,
      Currency.mxn: item.startPriceMxn,
      Currency.myr: item.startPriceMyr,
      Currency.ngn: item.startPriceNgn,
      Currency.npr: item.startPriceNpr,
      Currency.nzd: item.startPriceNzd,
      Currency.php: item.startPricePhp,
      Currency.pkr: item.startPricePkr,
      Currency.pln: item.startPricePln,
      Currency.qar: item.startPriceQar,
      Currency.ron: item.startPriceRon,
      Currency.rsd: item.startPriceRsd,
      Currency.sar: item.startPriceSar,
      Currency.sek: item.startPriceSek,
      Currency.sgd: item.startPriceSgd,
      Currency.thb: item.startPriceThb,
      Currency.tjs: item.startPriceTjs,
      Currency.zar: item.startPriceZar,
      Currency.uyu: item.startPriceUyu,
      Currency.chf: item.startPriceChf,
      Currency.nok: item.startPriceNok,
      Currency.rub: item.startPrice,
      Currency.gbp: item.startPriceGbp,
    };
    return startPrices[this];
  }

  double? getRegularPriceValue(PriceItem item) {
    final regularPrices = {
      Currency.clp: item.priceCl,
      Currency.eur: item.priceEu,
      Currency.pen: item.pricePen,
      Currency.usd: item.priceUsd,
      Currency.aed: item.priceAed,
      Currency.all: item.priceAll,
      Currency.amd: item.priceAmd,
      Currency.aoa: item.priceAoa,
      Currency.aud: item.priceAud,
      Currency.bam: item.priceBam,
      Currency.bdt: item.priceBdt,
      Currency.czk: item.priceCzk,
      Currency.dkk: item.priceDkk,
      Currency.dzd: item.priceDzd,
      Currency.egp: item.priceEgp,
      Currency.etb: item.priceEtb,
      Currency.gel: item.priceGel,
      Currency.hkd: item.priceHkd,
      Currency.huf: item.priceHuf,
      Currency.inr: item.priceInr,
      Currency.kes: item.priceKes,
      Currency.kgs: item.priceKgs,
      Currency.kzt: item.priceKzt,
      Currency.mad: item.priceMad,
      Currency.mdl: item.priceMdl,
      Currency.mxn: item.priceMxn,
      Currency.myr: item.priceMyr,
      Currency.ngn: item.priceNgn,
      Currency.npr: item.priceNpr,
      Currency.nzd: item.priceNzd,
      Currency.php: item.pricePhp,
      Currency.pkr: item.pricePkr,
      Currency.pln: item.pricePln,
      Currency.qar: item.priceQar,
      Currency.ron: item.priceRon,
      Currency.rsd: item.priceRsd,
      Currency.sar: item.priceSar,
      Currency.sek: item.priceSek,
      Currency.sgd: item.priceSgd,
      Currency.thb: item.priceThb,
      Currency.tjs: item.priceTjs,
      Currency.zar: item.priceZar,
      Currency.uyu: item.priceUyu,
      Currency.chf: item.priceChf,
      Currency.nok: item.priceNok,
      Currency.rub: item.price,
      Currency.gbp: item.priceGbp,
    };
    return regularPrices[this];
  }

  double? getDiscountPriceValue(PriceItem item) {
    final discountPrices = {
      Currency.clp: item.discountPriceCl,
      Currency.eur: item.discountPriceEu,
      Currency.pen: item.discountPricePen,
      Currency.usd: item.discountPriceUsd,
      Currency.aed: item.discountPriceAed,
      Currency.all: item.discountPriceAll,
      Currency.amd: item.discountPriceAmd,
      Currency.aoa: item.discountPriceAoa,
      Currency.aud: item.discountPriceAud,
      Currency.bam: item.discountPriceBam,
      Currency.bdt: item.discountPriceBdt,
      Currency.czk: item.discountPriceCzk,
      Currency.dkk: item.discountPriceDkk,
      Currency.dzd: item.discountPriceDzd,
      Currency.egp: item.discountPriceEgp,
      Currency.etb: item.discountPriceEtb,
      Currency.gel: item.discountPriceGel,
      Currency.hkd: item.discountPriceHkd,
      Currency.huf: item.discountPriceHuf,
      Currency.inr: item.discountPriceInr,
      Currency.kes: item.discountPriceKes,
      Currency.kgs: item.discountPriceKgs,
      Currency.kzt: item.discountPriceKzt,
      Currency.mad: item.discountPriceMad,
      Currency.mdl: item.discountPriceMdl,
      Currency.mxn: item.discountPriceMxn,
      Currency.myr: item.discountPriceMyr,
      Currency.ngn: item.discountPriceNgn,
      Currency.npr: item.discountPriceNpr,
      Currency.nzd: item.discountPriceNzd,
      Currency.php: item.discountPricePhp,
      Currency.pkr: item.discountPricePkr,
      Currency.pln: item.discountPricePln,
      Currency.qar: item.discountPriceQar,
      Currency.ron: item.discountPriceRon,
      Currency.rsd: item.discountPriceRsd,
      Currency.sar: item.discountPriceSar,
      Currency.sek: item.discountPriceSek,
      Currency.sgd: item.discountPriceSgd,
      Currency.thb: item.discountPriceThb,
      Currency.tjs: item.discountPriceTjs,
      Currency.zar: item.discountPriceZar,
      Currency.uyu: item.discountPriceUyu,
      Currency.chf: item.discountPriceChf,
      Currency.nok: item.discountPriceNok,
      Currency.rub: item.discountPrice,
      Currency.gbp: item.discountPriceGbp,
    };
    return discountPrices[this];
  }
}
