// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'price_item.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$PriceItemImpl _$$PriceItemImplFromJson(Map<String, dynamic> json) =>
    _$PriceItemImpl(
      id: json['id'] as String,
      name: json['name'] as String,
      price: (json['price'] as num?)?.toDouble(),
      priceEu: (json['priceEu'] as num?)?.toDouble(),
      startPriceEu: (json['startPriceEu'] as num?)?.toDouble(),
      discountPriceEu: (json['discountPriceEu'] as num?)?.toDouble(),
      discountStateEu: json['discountStateEu'] as bool?,
      priceUsd: (json['priceUsd'] as num?)?.toDouble(),
      startPriceUsd: (json['startPriceUsd'] as num?)?.toDouble(),
      discountPriceUsd: (json['discountPriceUsd'] as num?)?.toDouble(),
      discountStateUsd: json['discountStateUsd'] as bool?,
      pricePen: (json['pricePen'] as num?)?.toDouble(),
      startPricePen: (json['startPricePen'] as num?)?.toDouble(),
      discountPricePen: (json['discountPricePen'] as num?)?.toDouble(),
      discountStatePen: json['discountStatePen'] as bool?,
      priceAED: (json['priceAED'] as num?)?.toDouble(),
      priceGBP: (json['priceGBP'] as num?)?.toDouble(),
      priceJPY: (json['priceJPY'] as num?)?.toDouble(),
      category: json['category'] as String,
      discountState: json['discountState'] as bool,
      updatedAt: json['updatedAt'] == null
          ? null
          : DateTime.parse(json['updatedAt'] as String),
      priceCl: (json['priceCl'] as num?)?.toDouble(),
      priceAed: (json['priceAed'] as num?)?.toDouble(),
      priceAll: (json['priceAll'] as num?)?.toDouble(),
      priceAmd: (json['priceAmd'] as num?)?.toDouble(),
      priceAoa: (json['priceAoa'] as num?)?.toDouble(),
      priceAud: (json['priceAud'] as num?)?.toDouble(),
      priceBam: (json['priceBam'] as num?)?.toDouble(),
      priceBdt: (json['priceBdt'] as num?)?.toDouble(),
      priceCzk: (json['priceCzk'] as num?)?.toDouble(),
      priceDkk: (json['priceDkk'] as num?)?.toDouble(),
      priceDzd: (json['priceDzd'] as num?)?.toDouble(),
      priceEgp: (json['priceEgp'] as num?)?.toDouble(),
      priceEtb: (json['priceEtb'] as num?)?.toDouble(),
      priceGel: (json['priceGel'] as num?)?.toDouble(),
      priceHkd: (json['priceHkd'] as num?)?.toDouble(),
      priceHuf: (json['priceHuf'] as num?)?.toDouble(),
      priceInr: (json['priceInr'] as num?)?.toDouble(),
      priceKes: (json['priceKes'] as num?)?.toDouble(),
      priceKgs: (json['priceKgs'] as num?)?.toDouble(),
      priceKzt: (json['priceKzt'] as num?)?.toDouble(),
      priceMad: (json['priceMad'] as num?)?.toDouble(),
      priceMdl: (json['priceMdl'] as num?)?.toDouble(),
      priceMxn: (json['priceMxn'] as num?)?.toDouble(),
      priceMyr: (json['priceMyr'] as num?)?.toDouble(),
      priceNgn: (json['priceNgn'] as num?)?.toDouble(),
      priceNpr: (json['priceNpr'] as num?)?.toDouble(),
      priceNzd: (json['priceNzd'] as num?)?.toDouble(),
      pricePhp: (json['pricePhp'] as num?)?.toDouble(),
      pricePkr: (json['pricePkr'] as num?)?.toDouble(),
      pricePln: (json['pricePln'] as num?)?.toDouble(),
      priceQar: (json['priceQar'] as num?)?.toDouble(),
      priceRon: (json['priceRon'] as num?)?.toDouble(),
      priceRsd: (json['priceRsd'] as num?)?.toDouble(),
      priceSar: (json['priceSar'] as num?)?.toDouble(),
      priceSek: (json['priceSek'] as num?)?.toDouble(),
      priceSgd: (json['priceSgd'] as num?)?.toDouble(),
      priceThb: (json['priceThb'] as num?)?.toDouble(),
      priceTjs: (json['priceTjs'] as num?)?.toDouble(),
      priceZar: (json['priceZar'] as num?)?.toDouble(),
      priceUyu: (json['priceUyu'] as num?)?.toDouble(),
      priceChf: (json['priceChf'] as num?)?.toDouble(),
      priceNok: (json['priceNok'] as num?)?.toDouble(),
      startPriceCl: (json['startPriceCl'] as num?)?.toDouble(),
      discountPriceCl: (json['discountPriceCl'] as num?)?.toDouble(),
      discountStateCl: json['discountStateCl'] as bool?,
      startPriceAed: (json['startPriceAed'] as num?)?.toDouble(),
      discountPriceAed: (json['discountPriceAed'] as num?)?.toDouble(),
      discountStateAed: json['discountStateAed'] as bool?,
      startPriceAll: (json['startPriceAll'] as num?)?.toDouble(),
      discountPriceAll: (json['discountPriceAll'] as num?)?.toDouble(),
      discountStateAll: json['discountStateAll'] as bool?,
      startPriceAmd: (json['startPriceAmd'] as num?)?.toDouble(),
      discountPriceAmd: (json['discountPriceAmd'] as num?)?.toDouble(),
      discountStateAmd: json['discountStateAmd'] as bool?,
      startPriceAoa: (json['startPriceAoa'] as num?)?.toDouble(),
      discountPriceAoa: (json['discountPriceAoa'] as num?)?.toDouble(),
      discountStateAoa: json['discountStateAoa'] as bool?,
      startPriceAud: (json['startPriceAud'] as num?)?.toDouble(),
      discountPriceAud: (json['discountPriceAud'] as num?)?.toDouble(),
      discountStateAud: json['discountStateAud'] as bool?,
      startPriceBam: (json['startPriceBam'] as num?)?.toDouble(),
      discountPriceBam: (json['discountPriceBam'] as num?)?.toDouble(),
      discountStateBam: json['discountStateBam'] as bool?,
      startPriceBdt: (json['startPriceBdt'] as num?)?.toDouble(),
      discountPriceBdt: (json['discountPriceBdt'] as num?)?.toDouble(),
      discountStateBdt: json['discountStateBdt'] as bool?,
      startPriceCzk: (json['startPriceCzk'] as num?)?.toDouble(),
      discountPriceCzk: (json['discountPriceCzk'] as num?)?.toDouble(),
      discountStateCzk: json['discountStateCzk'] as bool?,
      startPriceDkk: (json['startPriceDkk'] as num?)?.toDouble(),
      discountPriceDkk: (json['discountPriceDkk'] as num?)?.toDouble(),
      discountStateDkk: json['discountStateDkk'] as bool?,
      startPriceDzd: (json['startPriceDzd'] as num?)?.toDouble(),
      discountPriceDzd: (json['discountPriceDzd'] as num?)?.toDouble(),
      discountStateDzd: json['discountStateDzd'] as bool?,
      startPriceEgp: (json['startPriceEgp'] as num?)?.toDouble(),
      discountPriceEgp: (json['discountPriceEgp'] as num?)?.toDouble(),
      discountStateEgp: json['discountStateEgp'] as bool?,
      startPriceEtb: (json['startPriceEtb'] as num?)?.toDouble(),
      discountPriceEtb: (json['discountPriceEtb'] as num?)?.toDouble(),
      discountStateEtb: json['discountStateEtb'] as bool?,
      startPriceGel: (json['startPriceGel'] as num?)?.toDouble(),
      discountPriceGel: (json['discountPriceGel'] as num?)?.toDouble(),
      discountStateGel: json['discountStateGel'] as bool?,
      startPriceHkd: (json['startPriceHkd'] as num?)?.toDouble(),
      discountPriceHkd: (json['discountPriceHkd'] as num?)?.toDouble(),
      discountStateHkd: json['discountStateHkd'] as bool?,
      startPriceHuf: (json['startPriceHuf'] as num?)?.toDouble(),
      discountPriceHuf: (json['discountPriceHuf'] as num?)?.toDouble(),
      discountStateHuf: json['discountStateHuf'] as bool?,
      startPriceInr: (json['startPriceInr'] as num?)?.toDouble(),
      discountPriceInr: (json['discountPriceInr'] as num?)?.toDouble(),
      discountStateInr: json['discountStateInr'] as bool?,
      startPriceKes: (json['startPriceKes'] as num?)?.toDouble(),
      discountPriceKes: (json['discountPriceKes'] as num?)?.toDouble(),
      discountStateKes: json['discountStateKes'] as bool?,
      startPriceKgs: (json['startPriceKgs'] as num?)?.toDouble(),
      discountPriceKgs: (json['discountPriceKgs'] as num?)?.toDouble(),
      discountStateKgs: json['discountStateKgs'] as bool?,
      startPriceKzt: (json['startPriceKzt'] as num?)?.toDouble(),
      discountPriceKzt: (json['discountPriceKzt'] as num?)?.toDouble(),
      discountStateKzt: json['discountStateKzt'] as bool?,
      startPriceMad: (json['startPriceMad'] as num?)?.toDouble(),
      discountPriceMad: (json['discountPriceMad'] as num?)?.toDouble(),
      discountStateMad: json['discountStateMad'] as bool?,
      startPriceMdl: (json['startPriceMdl'] as num?)?.toDouble(),
      discountPriceMdl: (json['discountPriceMdl'] as num?)?.toDouble(),
      discountStateMdl: json['discountStateMdl'] as bool?,
      startPriceMxn: (json['startPriceMxn'] as num?)?.toDouble(),
      discountPriceMxn: (json['discountPriceMxn'] as num?)?.toDouble(),
      discountStateMxn: json['discountStateMxn'] as bool?,
      startPriceMyr: (json['startPriceMyr'] as num?)?.toDouble(),
      discountPriceMyr: (json['discountPriceMyr'] as num?)?.toDouble(),
      discountStateMyr: json['discountStateMyr'] as bool?,
      startPriceNgn: (json['startPriceNgn'] as num?)?.toDouble(),
      discountPriceNgn: (json['discountPriceNgn'] as num?)?.toDouble(),
      discountStateNgn: json['discountStateNgn'] as bool?,
      startPriceNpr: (json['startPriceNpr'] as num?)?.toDouble(),
      discountPriceNpr: (json['discountPriceNpr'] as num?)?.toDouble(),
      discountStateNpr: json['discountStateNpr'] as bool?,
      startPriceNzd: (json['startPriceNzd'] as num?)?.toDouble(),
      discountPriceNzd: (json['discountPriceNzd'] as num?)?.toDouble(),
      discountStateNzd: json['discountStateNzd'] as bool?,
      startPricePhp: (json['startPricePhp'] as num?)?.toDouble(),
      discountPricePhp: (json['discountPricePhp'] as num?)?.toDouble(),
      discountStatePhp: json['discountStatePhp'] as bool?,
      startPricePkr: (json['startPricePkr'] as num?)?.toDouble(),
      discountPricePkr: (json['discountPricePkr'] as num?)?.toDouble(),
      discountStatePkr: json['discountStatePkr'] as bool?,
      startPricePln: (json['startPricePln'] as num?)?.toDouble(),
      discountPricePln: (json['discountPricePln'] as num?)?.toDouble(),
      discountStatePln: json['discountStatePln'] as bool?,
      startPriceQar: (json['startPriceQar'] as num?)?.toDouble(),
      discountPriceQar: (json['discountPriceQar'] as num?)?.toDouble(),
      discountStateQar: json['discountStateQar'] as bool?,
      startPriceRon: (json['startPriceRon'] as num?)?.toDouble(),
      discountPriceRon: (json['discountPriceRon'] as num?)?.toDouble(),
      discountStateRon: json['discountStateRon'] as bool?,
      startPriceRsd: (json['startPriceRsd'] as num?)?.toDouble(),
      discountPriceRsd: (json['discountPriceRsd'] as num?)?.toDouble(),
      discountStateRsd: json['discountStateRsd'] as bool?,
      startPriceSar: (json['startPriceSar'] as num?)?.toDouble(),
      discountPriceSar: (json['discountPriceSar'] as num?)?.toDouble(),
      discountStateSar: json['discountStateSar'] as bool?,
      startPriceSek: (json['startPriceSek'] as num?)?.toDouble(),
      discountPriceSek: (json['discountPriceSek'] as num?)?.toDouble(),
      discountStateSek: json['discountStateSek'] as bool?,
      startPriceSgd: (json['startPriceSgd'] as num?)?.toDouble(),
      discountPriceSgd: (json['discountPriceSgd'] as num?)?.toDouble(),
      discountStateSgd: json['discountStateSgd'] as bool?,
      startPriceThb: (json['startPriceThb'] as num?)?.toDouble(),
      discountPriceThb: (json['discountPriceThb'] as num?)?.toDouble(),
      discountStateThb: json['discountStateThb'] as bool?,
      startPriceTjs: (json['startPriceTjs'] as num?)?.toDouble(),
      discountPriceTjs: (json['discountPriceTjs'] as num?)?.toDouble(),
      discountStateTjs: json['discountStateTjs'] as bool?,
      startPriceZar: (json['startPriceZar'] as num?)?.toDouble(),
      discountPriceZar: (json['discountPriceZar'] as num?)?.toDouble(),
      discountStateZar: json['discountStateZar'] as bool?,
      startPriceUyu: (json['startPriceUyu'] as num?)?.toDouble(),
      discountPriceUyu: (json['discountPriceUyu'] as num?)?.toDouble(),
      discountStateUyu: json['discountStateUyu'] as bool?,
      startPriceChf: (json['startPriceChf'] as num?)?.toDouble(),
      discountPriceChf: (json['discountPriceChf'] as num?)?.toDouble(),
      discountStateChf: json['discountStateChf'] as bool?,
      startPriceNok: (json['startPriceNok'] as num?)?.toDouble(),
      discountPriceNok: (json['discountPriceNok'] as num?)?.toDouble(),
      discountStateNok: json['discountStateNok'] as bool?,
      startPriceGbp: (json['startPriceGbp'] as num?)?.toDouble(),
      discountPriceGbp: (json['discountPriceGbp'] as num?)?.toDouble(),
      discountStateGbp: json['discountStateGbp'] as bool?,
    );

Map<String, dynamic> _$$PriceItemImplToJson(_$PriceItemImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'price': instance.price,
      'priceEu': instance.priceEu,
      'startPriceEu': instance.startPriceEu,
      'discountPriceEu': instance.discountPriceEu,
      'discountStateEu': instance.discountStateEu,
      'priceUsd': instance.priceUsd,
      'startPriceUsd': instance.startPriceUsd,
      'discountPriceUsd': instance.discountPriceUsd,
      'discountStateUsd': instance.discountStateUsd,
      'pricePen': instance.pricePen,
      'startPricePen': instance.startPricePen,
      'discountPricePen': instance.discountPricePen,
      'discountStatePen': instance.discountStatePen,
      'priceAED': instance.priceAED,
      'priceGBP': instance.priceGBP,
      'priceJPY': instance.priceJPY,
      'category': instance.category,
      'discountState': instance.discountState,
      'updatedAt': instance.updatedAt?.toIso8601String(),
      'priceCl': instance.priceCl,
      'priceAed': instance.priceAed,
      'priceAll': instance.priceAll,
      'priceAmd': instance.priceAmd,
      'priceAoa': instance.priceAoa,
      'priceAud': instance.priceAud,
      'priceBam': instance.priceBam,
      'priceBdt': instance.priceBdt,
      'priceCzk': instance.priceCzk,
      'priceDkk': instance.priceDkk,
      'priceDzd': instance.priceDzd,
      'priceEgp': instance.priceEgp,
      'priceEtb': instance.priceEtb,
      'priceGel': instance.priceGel,
      'priceHkd': instance.priceHkd,
      'priceHuf': instance.priceHuf,
      'priceInr': instance.priceInr,
      'priceKes': instance.priceKes,
      'priceKgs': instance.priceKgs,
      'priceKzt': instance.priceKzt,
      'priceMad': instance.priceMad,
      'priceMdl': instance.priceMdl,
      'priceMxn': instance.priceMxn,
      'priceMyr': instance.priceMyr,
      'priceNgn': instance.priceNgn,
      'priceNpr': instance.priceNpr,
      'priceNzd': instance.priceNzd,
      'pricePhp': instance.pricePhp,
      'pricePkr': instance.pricePkr,
      'pricePln': instance.pricePln,
      'priceQar': instance.priceQar,
      'priceRon': instance.priceRon,
      'priceRsd': instance.priceRsd,
      'priceSar': instance.priceSar,
      'priceSek': instance.priceSek,
      'priceSgd': instance.priceSgd,
      'priceThb': instance.priceThb,
      'priceTjs': instance.priceTjs,
      'priceZar': instance.priceZar,
      'priceUyu': instance.priceUyu,
      'priceChf': instance.priceChf,
      'priceNok': instance.priceNok,
      'startPriceCl': instance.startPriceCl,
      'discountPriceCl': instance.discountPriceCl,
      'discountStateCl': instance.discountStateCl,
      'startPriceAed': instance.startPriceAed,
      'discountPriceAed': instance.discountPriceAed,
      'discountStateAed': instance.discountStateAed,
      'startPriceAll': instance.startPriceAll,
      'discountPriceAll': instance.discountPriceAll,
      'discountStateAll': instance.discountStateAll,
      'startPriceAmd': instance.startPriceAmd,
      'discountPriceAmd': instance.discountPriceAmd,
      'discountStateAmd': instance.discountStateAmd,
      'startPriceAoa': instance.startPriceAoa,
      'discountPriceAoa': instance.discountPriceAoa,
      'discountStateAoa': instance.discountStateAoa,
      'startPriceAud': instance.startPriceAud,
      'discountPriceAud': instance.discountPriceAud,
      'discountStateAud': instance.discountStateAud,
      'startPriceBam': instance.startPriceBam,
      'discountPriceBam': instance.discountPriceBam,
      'discountStateBam': instance.discountStateBam,
      'startPriceBdt': instance.startPriceBdt,
      'discountPriceBdt': instance.discountPriceBdt,
      'discountStateBdt': instance.discountStateBdt,
      'startPriceCzk': instance.startPriceCzk,
      'discountPriceCzk': instance.discountPriceCzk,
      'discountStateCzk': instance.discountStateCzk,
      'startPriceDkk': instance.startPriceDkk,
      'discountPriceDkk': instance.discountPriceDkk,
      'discountStateDkk': instance.discountStateDkk,
      'startPriceDzd': instance.startPriceDzd,
      'discountPriceDzd': instance.discountPriceDzd,
      'discountStateDzd': instance.discountStateDzd,
      'startPriceEgp': instance.startPriceEgp,
      'discountPriceEgp': instance.discountPriceEgp,
      'discountStateEgp': instance.discountStateEgp,
      'startPriceEtb': instance.startPriceEtb,
      'discountPriceEtb': instance.discountPriceEtb,
      'discountStateEtb': instance.discountStateEtb,
      'startPriceGel': instance.startPriceGel,
      'discountPriceGel': instance.discountPriceGel,
      'discountStateGel': instance.discountStateGel,
      'startPriceHkd': instance.startPriceHkd,
      'discountPriceHkd': instance.discountPriceHkd,
      'discountStateHkd': instance.discountStateHkd,
      'startPriceHuf': instance.startPriceHuf,
      'discountPriceHuf': instance.discountPriceHuf,
      'discountStateHuf': instance.discountStateHuf,
      'startPriceInr': instance.startPriceInr,
      'discountPriceInr': instance.discountPriceInr,
      'discountStateInr': instance.discountStateInr,
      'startPriceKes': instance.startPriceKes,
      'discountPriceKes': instance.discountPriceKes,
      'discountStateKes': instance.discountStateKes,
      'startPriceKgs': instance.startPriceKgs,
      'discountPriceKgs': instance.discountPriceKgs,
      'discountStateKgs': instance.discountStateKgs,
      'startPriceKzt': instance.startPriceKzt,
      'discountPriceKzt': instance.discountPriceKzt,
      'discountStateKzt': instance.discountStateKzt,
      'startPriceMad': instance.startPriceMad,
      'discountPriceMad': instance.discountPriceMad,
      'discountStateMad': instance.discountStateMad,
      'startPriceMdl': instance.startPriceMdl,
      'discountPriceMdl': instance.discountPriceMdl,
      'discountStateMdl': instance.discountStateMdl,
      'startPriceMxn': instance.startPriceMxn,
      'discountPriceMxn': instance.discountPriceMxn,
      'discountStateMxn': instance.discountStateMxn,
      'startPriceMyr': instance.startPriceMyr,
      'discountPriceMyr': instance.discountPriceMyr,
      'discountStateMyr': instance.discountStateMyr,
      'startPriceNgn': instance.startPriceNgn,
      'discountPriceNgn': instance.discountPriceNgn,
      'discountStateNgn': instance.discountStateNgn,
      'startPriceNpr': instance.startPriceNpr,
      'discountPriceNpr': instance.discountPriceNpr,
      'discountStateNpr': instance.discountStateNpr,
      'startPriceNzd': instance.startPriceNzd,
      'discountPriceNzd': instance.discountPriceNzd,
      'discountStateNzd': instance.discountStateNzd,
      'startPricePhp': instance.startPricePhp,
      'discountPricePhp': instance.discountPricePhp,
      'discountStatePhp': instance.discountStatePhp,
      'startPricePkr': instance.startPricePkr,
      'discountPricePkr': instance.discountPricePkr,
      'discountStatePkr': instance.discountStatePkr,
      'startPricePln': instance.startPricePln,
      'discountPricePln': instance.discountPricePln,
      'discountStatePln': instance.discountStatePln,
      'startPriceQar': instance.startPriceQar,
      'discountPriceQar': instance.discountPriceQar,
      'discountStateQar': instance.discountStateQar,
      'startPriceRon': instance.startPriceRon,
      'discountPriceRon': instance.discountPriceRon,
      'discountStateRon': instance.discountStateRon,
      'startPriceRsd': instance.startPriceRsd,
      'discountPriceRsd': instance.discountPriceRsd,
      'discountStateRsd': instance.discountStateRsd,
      'startPriceSar': instance.startPriceSar,
      'discountPriceSar': instance.discountPriceSar,
      'discountStateSar': instance.discountStateSar,
      'startPriceSek': instance.startPriceSek,
      'discountPriceSek': instance.discountPriceSek,
      'discountStateSek': instance.discountStateSek,
      'startPriceSgd': instance.startPriceSgd,
      'discountPriceSgd': instance.discountPriceSgd,
      'discountStateSgd': instance.discountStateSgd,
      'startPriceThb': instance.startPriceThb,
      'discountPriceThb': instance.discountPriceThb,
      'discountStateThb': instance.discountStateThb,
      'startPriceTjs': instance.startPriceTjs,
      'discountPriceTjs': instance.discountPriceTjs,
      'discountStateTjs': instance.discountStateTjs,
      'startPriceZar': instance.startPriceZar,
      'discountPriceZar': instance.discountPriceZar,
      'discountStateZar': instance.discountStateZar,
      'startPriceUyu': instance.startPriceUyu,
      'discountPriceUyu': instance.discountPriceUyu,
      'discountStateUyu': instance.discountStateUyu,
      'startPriceChf': instance.startPriceChf,
      'discountPriceChf': instance.discountPriceChf,
      'discountStateChf': instance.discountStateChf,
      'startPriceNok': instance.startPriceNok,
      'discountPriceNok': instance.discountPriceNok,
      'discountStateNok': instance.discountStateNok,
      'startPriceGbp': instance.startPriceGbp,
      'discountPriceGbp': instance.discountPriceGbp,
      'discountStateGbp': instance.discountStateGbp,
    };
